=head1 NAME

README - Readme file for the conversion of 'docs.parrot.org' to github pages.

=head1 DESCRIPTION

This README sets out the reason for the relocation of Parrot's documentation,
which ordinarily resides on 'docs.parrot.org', to [Github
pages](http://pages.github.com).  The basic idea is to make editing of the
documentation more readily accessible.  That is, with these pages now up on
github, folks can more easily fix or, alternatively provide pull requests to
correct any errors in the documentation.

So, everyone, feel free to contribute!

=head1 COPYRIGHT

Copyright (C) 2011, Parrot Foundation.

=cut
