# Copyright (C) 2012, Parrot Foundation

=pod

=head1 NAME

README_release.pod - Readme file on how to maintain the 'parrot.github.com' 
gh-pages repository and its supporing 'parrot-docsx' repositories.

=head1 DESCRIPTION

This document is a guide on how to maintain 

Maintaining the gh-pages branch of the 'parrot.github.com' repository is not 
overly difficult, but it can be a'bit tricky.  Hence, the need for this 
release guide.

=head1 COPYRIGHT

Copyright (C) 2001-2011, Parrot Foundation.

=cut
